// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Public
 */
export function GetAllShortcuts(): $CancellablePromise<$models.Shortcut[]> {
    return $Call.ByID(3692551782).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetShortcutCombo(action: string): $CancellablePromise<string> {
    return $Call.ByID(3957169132, action);
}

export function GetShortcutCombos(actions: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(3973839693, actions).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ResetAllShortcuts(): $CancellablePromise<void> {
    return $Call.ByID(3475915305);
}

export function ResetShortcut(action: string): $CancellablePromise<void> {
    return $Call.ByID(55329345, action);
}

export function UpdateShortcut(action: string, newKeyCombo: string): $CancellablePromise<void> {
    return $Call.ByID(1392324355, action, newKeyCombo);
}

// Private type creation functions
const $$createType0 = $models.Shortcut.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
