// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Returns cached results when fresh; otherwise fetches the manifest.
 * Concurrent callers wait for the single in-flight request to
 * finish before reading from the cache.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(3866282951).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Downloads the artifact and runs the platform installer
 */
export function DownloadAndInstall(downloadURL: string): $CancellablePromise<void> {
    return $Call.ByID(1729477037, downloadURL);
}

export function RestartApp(): $CancellablePromise<void> {
    return $Call.ByID(549130507);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
