// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as reflectx$0 from "./reflectx/models.js";

/**
 * DB is a wrapper around sql.DB which keeps track of the driverName upon Open,
 * used mostly to automatically bind named queries using the right bindvars.
 */
export class DB {
    "Mapper": reflectx$0.Mapper | null;

    /** Creates a new DB instance. */
    constructor($$source: Partial<DB> = {}) {
        if (!("Mapper" in $$source)) {
            this["Mapper"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DB instance from a string or object.
     */
    static createFrom($$source: any = {}): DB {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mapper" in $$parsedSource) {
            $$parsedSource["Mapper"] = $$createField0_0($$parsedSource["Mapper"]);
        }
        return new DB($$parsedSource as Partial<DB>);
    }
}

// Private type creation functions
const $$createType0 = reflectx$0.Mapper.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
