// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mapper is a general purpose mapper of names to struct fields.  A Mapper
 * behaves like most marshallers in the standard library, obeying a field tag
 * for name mapping but also providing a basic transform function.
 */
export class Mapper {

    /** Creates a new Mapper instance. */
    constructor($$source: Partial<Mapper> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mapper instance from a string or object.
     */
    static createFrom($$source: any = {}): Mapper {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mapper($$parsedSource as Partial<Mapper>);
    }
}
