// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Print {
    "id": number;
    "name": string;
    "status": string;
    "notes": string;
    "datePrinted": time$0.Time | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * join table
     */
    "spools"?: PrintSpool[];

    /** Creates a new Print instance. */
    constructor($$source: Partial<Print> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("datePrinted" in $$source)) {
            this["datePrinted"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Print instance from a string or object.
     */
    static createFrom($$source: any = {}): Print {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spools" in $$parsedSource) {
            $$parsedSource["spools"] = $$createField7_0($$parsedSource["spools"]);
        }
        return new Print($$parsedSource as Partial<Print>);
    }
}

export class PrintQueryParams {
    "search": string;
    "status": string;
    "sortBy": string;
    "sortOrder": string;
    "limit": number;
    "offset": number;

    /** Creates a new PrintQueryParams instance. */
    constructor($$source: Partial<PrintQueryParams> = {}) {
        if (!("search" in $$source)) {
            this["search"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrintQueryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): PrintQueryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PrintQueryParams($$parsedSource as Partial<PrintQueryParams>);
    }
}

export class PrintQueryResult {
    "prints": Print[];
    "total": number;

    /** Creates a new PrintQueryResult instance. */
    constructor($$source: Partial<PrintQueryResult> = {}) {
        if (!("prints" in $$source)) {
            this["prints"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrintQueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PrintQueryResult {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("prints" in $$parsedSource) {
            $$parsedSource["prints"] = $$createField0_0($$parsedSource["prints"]);
        }
        return new PrintQueryResult($$parsedSource as Partial<PrintQueryResult>);
    }
}

export class PrintSpool {
    "id": number;
    "printId": number;
    "spoolId": number;
    "gramsUsed": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;
    "spool"?: Spool | null;

    /** Creates a new PrintSpool instance. */
    constructor($$source: Partial<PrintSpool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("printId" in $$source)) {
            this["printId"] = 0;
        }
        if (!("spoolId" in $$source)) {
            this["spoolId"] = 0;
        }
        if (!("gramsUsed" in $$source)) {
            this["gramsUsed"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PrintSpool instance from a string or object.
     */
    static createFrom($$source: any = {}): PrintSpool {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spool" in $$parsedSource) {
            $$parsedSource["spool"] = $$createField6_0($$parsedSource["spool"]);
        }
        return new PrintSpool($$parsedSource as Partial<PrintSpool>);
    }
}

export class Shortcut {
    "id": number;
    "action": string;
    "keyCombo": string;
    "description": string;
    "category": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Shortcut instance. */
    constructor($$source: Partial<Shortcut> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("keyCombo" in $$source)) {
            this["keyCombo"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Shortcut instance from a string or object.
     */
    static createFrom($$source: any = {}): Shortcut {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Shortcut($$parsedSource as Partial<Shortcut>);
    }
}

export class Spool {
    "id": number;
    "spoolCode": string;
    "vendor": string;
    "material": string;
    "materialType": string;
    "color": string;
    "colorHex": string;
    "totalWeight": number;
    "usedWeight": number;
    "cost": number;
    "referenceLink": string;
    "notes": string;
    "isTemplate": boolean;
    "firstUsedAt": time$0.Time | null;
    "lastUsedAt": time$0.Time | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Spool instance. */
    constructor($$source: Partial<Spool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("spoolCode" in $$source)) {
            this["spoolCode"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("material" in $$source)) {
            this["material"] = "";
        }
        if (!("materialType" in $$source)) {
            this["materialType"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("colorHex" in $$source)) {
            this["colorHex"] = "";
        }
        if (!("totalWeight" in $$source)) {
            this["totalWeight"] = 0;
        }
        if (!("usedWeight" in $$source)) {
            this["usedWeight"] = 0;
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("referenceLink" in $$source)) {
            this["referenceLink"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("isTemplate" in $$source)) {
            this["isTemplate"] = false;
        }
        if (!("firstUsedAt" in $$source)) {
            this["firstUsedAt"] = null;
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spool instance from a string or object.
     */
    static createFrom($$source: any = {}): Spool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spool($$parsedSource as Partial<Spool>);
    }
}

export class SpoolQueryParams {
    "search": string;
    "material": string;
    "vendor": string;
    "isTemplate": boolean | null;
    "sortBy": string;
    "sortOrder": string;
    "limit": number;
    "offset": number;

    /** Creates a new SpoolQueryParams instance. */
    constructor($$source: Partial<SpoolQueryParams> = {}) {
        if (!("search" in $$source)) {
            this["search"] = "";
        }
        if (!("material" in $$source)) {
            this["material"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("isTemplate" in $$source)) {
            this["isTemplate"] = null;
        }
        if (!("sortBy" in $$source)) {
            this["sortBy"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpoolQueryParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SpoolQueryParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SpoolQueryParams($$parsedSource as Partial<SpoolQueryParams>);
    }
}

export class SpoolQueryResult {
    "spools": Spool[];
    "total": number;

    /** Creates a new SpoolQueryResult instance. */
    constructor($$source: Partial<SpoolQueryResult> = {}) {
        if (!("spools" in $$source)) {
            this["spools"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SpoolQueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SpoolQueryResult {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("spools" in $$parsedSource) {
            $$parsedSource["spools"] = $$createField0_0($$parsedSource["spools"]);
        }
        return new SpoolQueryResult($$parsedSource as Partial<SpoolQueryResult>);
    }
}

// Private type creation functions
const $$createType0 = PrintSpool.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Print.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Spool.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType4);
