// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Print {
    "id": number;
    "name": string;
    "spoolId": number;
    "gramsUsed": number;
    "status": string;
    "notes": string;
    "datePrinted": time$0.Time | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Print instance. */
    constructor($$source: Partial<Print> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("spoolId" in $$source)) {
            this["spoolId"] = 0;
        }
        if (!("gramsUsed" in $$source)) {
            this["gramsUsed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("datePrinted" in $$source)) {
            this["datePrinted"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Print instance from a string or object.
     */
    static createFrom($$source: any = {}): Print {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Print($$parsedSource as Partial<Print>);
    }
}

export class Spool {
    "id": number;
    "spoolCode": string;
    "vendor": string;
    "material": string;
    "materialType": string;
    "color": string;
    "colorHex": string;
    "totalWeight": number;
    "usedWeight": number;
    "cost": number;
    "referenceLink": string;
    "notes": string;
    "isTemplate": boolean;
    "firstUsedAt": time$0.Time | null;
    "lastUsedAt": time$0.Time | null;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Spool instance. */
    constructor($$source: Partial<Spool> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("spoolCode" in $$source)) {
            this["spoolCode"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = "";
        }
        if (!("material" in $$source)) {
            this["material"] = "";
        }
        if (!("materialType" in $$source)) {
            this["materialType"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("colorHex" in $$source)) {
            this["colorHex"] = "";
        }
        if (!("totalWeight" in $$source)) {
            this["totalWeight"] = 0;
        }
        if (!("usedWeight" in $$source)) {
            this["usedWeight"] = 0;
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("referenceLink" in $$source)) {
            this["referenceLink"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("isTemplate" in $$source)) {
            this["isTemplate"] = false;
        }
        if (!("firstUsedAt" in $$source)) {
            this["firstUsedAt"] = null;
        }
        if (!("lastUsedAt" in $$source)) {
            this["lastUsedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Spool instance from a string or object.
     */
    static createFrom($$source: any = {}): Spool {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Spool($$parsedSource as Partial<Spool>);
    }
}
