// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreatePrint(p: $models.Print): $CancellablePromise<number> {
    return $Call.ByID(2366661757, p);
}

export function DeletePrint(id: number, deletePrintSpools: boolean): $CancellablePromise<void> {
    return $Call.ByID(1451455108, id, deletePrintSpools);
}

export function DeletePrintModel(printID: number, modelID: number, modelExt: string): $CancellablePromise<void> {
    return $Call.ByID(3103083793, printID, modelID, modelExt);
}

export function DuplicatePrintModel(printID: number, modelID: number): $CancellablePromise<$models.PrintModel | null> {
    return $Call.ByID(1846966371, printID, modelID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetPrintModels(printID: number): $CancellablePromise<$models.PrintModel[]> {
    return $Call.ByID(134154019, printID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * New query method with filtering, sorting, and pagination
 */
export function QueryPrints(params: $models.PrintQueryParams): $CancellablePromise<$models.PrintQueryResult | null> {
    return $Call.ByID(3055920690, params).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdatePrint(p: $models.Print): $CancellablePromise<void> {
    return $Call.ByID(141751710, p);
}

export function UploadPrintModel(printID: number, fileName: string, ext: string, size: number, data: string): $CancellablePromise<$models.PrintModel | null> {
    return $Call.ByID(2005807887, printID, fileName, ext, size, data).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PrintModel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.PrintQueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
