// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreatePrint(p: $models.Print): $CancellablePromise<number> {
    return $Call.ByID(2366661757, p);
}

export function DeletePrint(id: number, deletePrintSpools: boolean): $CancellablePromise<void> {
    return $Call.ByID(1451455108, id, deletePrintSpools);
}

export function GetPrint(id: number): $CancellablePromise<$models.Print | null> {
    return $Call.ByID(3750870029, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Legacy method - kept for backward compatibility
 */
export function ListPrints(): $CancellablePromise<$models.Print[]> {
    return $Call.ByID(2001335930).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * New query method with filtering, sorting, and pagination
 */
export function QueryPrints(params: $models.PrintQueryParams): $CancellablePromise<$models.PrintQueryResult | null> {
    return $Call.ByID(3055920690, params).then(($result: any) => {
        return $$createType4($result);
    });
}

export function UpdatePrint(p: $models.Print): $CancellablePromise<void> {
    return $Call.ByID(141751710, p);
}

// Private type creation functions
const $$createType0 = $models.Print.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.PrintQueryResult.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
