// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetAllShortcuts(): $CancellablePromise<$models.Shortcut[]> {
    return $Call.ByID(4272727815).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetShortcutCombo(action: string): $CancellablePromise<string> {
    return $Call.ByID(2640683523, action);
}

export function GetShortcutsByCategory(category: string): $CancellablePromise<$models.Shortcut[]> {
    return $Call.ByID(1746004273, category).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Name(): $CancellablePromise<string> {
    return $Call.ByID(2206458040);
}

export function ResetAllShortcuts(): $CancellablePromise<void> {
    return $Call.ByID(4167460956);
}

export function ResetShortcut(action: string): $CancellablePromise<void> {
    return $Call.ByID(589397084, action);
}

export function UpdateShortcut(action: string, newKeyCombo: string): $CancellablePromise<void> {
    return $Call.ByID(23993756, action, newKeyCombo);
}

// Private type creation functions
const $$createType0 = $models.Shortcut.createFrom;
const $$createType1 = $Create.Array($$createType0);
