// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateSpool(spool: $models.Spool): $CancellablePromise<number> {
    return $Call.ByID(3723822317, spool);
}

export function DeleteSpool(id: number): $CancellablePromise<void> {
    return $Call.ByID(4240370512, id);
}

export function GetSpool(id: number): $CancellablePromise<$models.Spool | null> {
    return $Call.ByID(1722505621, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSpoolByCode(code: string): $CancellablePromise<$models.Spool | null> {
    return $Call.ByID(2094543505, code).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ListSpools(): $CancellablePromise<$models.Spool[]> {
    return $Call.ByID(2639247538).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateSpool(spool: $models.Spool): $CancellablePromise<void> {
    return $Call.ByID(708113630, spool);
}

// Private type creation functions
const $$createType0 = $models.Spool.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
