// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateSpool(spool: $models.Spool): $CancellablePromise<number> {
    return $Call.ByID(3723822317, spool);
}

export function DeleteSpool(id: number): $CancellablePromise<void> {
    return $Call.ByID(4240370512, id);
}

export function GetSpoolPrints(spoolID: number): $CancellablePromise<$models.SpoolPrint[]> {
    return $Call.ByID(934640337, spoolID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function QuerySpools(params: $models.SpoolQueryParams): $CancellablePromise<$models.SpoolQueryResult | null> {
    return $Call.ByID(2723076002, params).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdateSpool(spool: $models.Spool): $CancellablePromise<void> {
    return $Call.ByID(708113630, spool);
}

// Private type creation functions
const $$createType0 = $models.SpoolPrint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.SpoolQueryResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
