// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sqlx$0 from "../../../github.com/jmoiron/sqlx/models.js";

export function DB(): $CancellablePromise<sqlx$0.DB | null> {
    return $Call.ByID(3400910839).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = sqlx$0.DB.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
