// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreatePrint(p: $models.Print): $CancellablePromise<number> {
    return $Call.ByID(31737063, p);
}

export function DeletePrint(id: number, restoreSpoolGrams: boolean): $CancellablePromise<void> {
    return $Call.ByID(1247878790, id, restoreSpoolGrams);
}

export function DeletePrintModel(printID: number, modelID: number): $CancellablePromise<void> {
    return $Call.ByID(75931923, printID, modelID);
}

export function DuplicatePrintModel(printID: number, modelID: number): $CancellablePromise<void> {
    return $Call.ByID(3796094437, printID, modelID);
}

export function GetPrintModels(printID: number): $CancellablePromise<$models.PrintModel[]> {
    return $Call.ByID(4192761797, printID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function QueryPrints(params: $models.PrintQueryParams): $CancellablePromise<$models.PrintQueryResult | null> {
    return $Call.ByID(223780716, params).then(($result: any) => {
        return $$createType3($result);
    });
}

export function UpdatePrint(p: $models.Print): $CancellablePromise<void> {
    return $Call.ByID(1874011736, p);
}

export function UploadPrintModel(printID: number, fileName: string, ext: string, size: number, data: string): $CancellablePromise<void> {
    return $Call.ByID(1986546053, printID, fileName, ext, size, data);
}

// Private type creation functions
const $$createType0 = $models.PrintModel.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PrintQueryResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
