// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckForUpdate fetches the manifest and returns update info.
 * Called from the frontend via Wails bindings.
 */
export function CheckForUpdate(): $CancellablePromise<$models.UpdateInfo | null> {
    return $Call.ByID(734489184).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DownloadAndInstall downloads the update and launches the installer / replaces the binary.
 * On Windows: downloads .exe installer and runs it (NSIS/Inno Setup style).
 * On macOS: downloads .dmg and opens it.
 * On Linux: downloads binary, else AppImage, makes it executable, replaces current binary.
 */
export function DownloadAndInstall(downloadURL: string): $CancellablePromise<void> {
    return $Call.ByID(744075698, downloadURL);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
