export const DEFAULT_SPOOL_VENDORS = [
    "Bambu Lab",
    "Prusa Research",
    "Creality",
    "Elegoo",
    "Anycubic",
    "FlashForge",
    "UltiMaker",
    "Raise3D",
    "Formlabs",
    "MakerBot",
    "Zortrax",
    "QIDI Tech",
    "Artillery",
    "Snapmaker",
    "Mingda",
    "Tronxy",
    "Tevo",
    "BIQU",
    "Fokoos",
    "AnkerMake",
    "Anycubic Kobra",
    "Phrozen",
    "Peopoly",
    "EPAX",
    "Rat Rig",
    "Voron Design",
    "LulzBot",
    "Robo 3D",
    "LulzBot TAZ",
    "Geeetech",
    "Modix",
    "INTAMSYS",
    "Tiertime (UP)",
    "Dremel 3D",
    "XYZprinting",
    "WASP",
    "Markforged",
    "Stratasys",
    "3D Systems",
    "UnionTech",
];

export const DEFAULT_SPOOL_MATERIALS = [
    "PLA",
    "ABS",
    "PET",
    "PETG",
    "PCTG",
    "Nylon",
    "TPU",
    "TPE",
    "ASA",
    "HIPS",
    "PVA",
    "PC",
    "PC‑ABS",
    "PP",
    "PVB",
    "PLA‑Pro",
    "PLA‑CF",
    "PETG‑CF",
    "PA12‑CF",
    "PA12‑GF",
    "PLA‑Wood",
    "PLA‑Metal",
    "Silk PLA",
    "Glow‑in‑the‑Dark",
    "Conductive PLA",
];

export const DEFAULT_SPOOL_MATERIALTYPES = [
    "Basic",
    "Silk",
    "Matte",
    "Wood",
    "Metal",
    "Carbon Fiber",
    "Composite",
    "Flexible",
    "Support",
    "Engineering",
    "Special Effects",
];

export const DEFAULT_SPOOL_COLORS = [
    "Black",
    "White",
    "Gray",
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
    "Pink",
    "Brown",
    "Beige",
    "Cyan",
    "Magenta",
    "Turquoise",
    "Gold",
    "Silver",
    "Copper",
    "Transparent",
    "Clear",
];
