import type { AppOptions } from "@/context/useContext";

// https://3dfilamentprofiles.com/brands?perPage=100&sort=spools_d
export const DEFAULT_SPOOL_VENDORS = [
    "Bambu Lab",
    "SUNLU",
    "ELEGOO",
    "eSUN",
    "Polymaker",
    "Overture",
    "Creality",
    "Jayo",
    "Anycubic",
    "Inland",
    "Kingroon",
    "Eryone",
    "Geeetech",
    "FlashForge",
    "Amolen",
    "DEEPLEE",
    "TecBears",
    "CC3D",
    "Amazon Basics",
    "SOLEYIN",
    "Hatchbox",
    "Prusament",
    "3DHoJor",
    "Tinmorry",
    "Ziro",
    "PanChroma",
    "add:north",
    "Giantarm",
    "Extrudr",
    "Protopasta",
    "Cookiecad",
    "iSanmate",
    "Siddament",
    "Ambrosia",
    "Hobby Lobby",
    "Aceaddity",
    "Alchemakes",
    "kexcelled",
    "Numakers",
    "VOXELPLA",
    "Snapmaker",
    "IIID Max",
    "Ender",
    "Generic",
    "Atomic Filament",
    "Spectrum",
    "3D-Fuel",
    "Mika3D",
    "Rosa3D",
    "OVV3D",
    "3DJake",
    "IEMAI",
    "Clas Ohlson",
    "SmartMaterials",
    "AzureFilm",
    "GST 3D",
    "MarsWork",
    "DURAMIC 3D",
    "Matterhackers",
    "Comgrow",
    "Inslogic",
    "Yousu",
    "AURAPOL",
    "Paramount 3D",
    "Fiberlogy",
    "Nobufil",
    "Fiberon",
    "Recycling Fabrik",
    "Stronghero3d",
    "R3D",
    "Filament Unger",
    "Devil Design",
    "Siraya Tech",
    "Fillamentum",
    "3D Printing Canada",
    "QIDI Tech",
    "Zyltech",
    "Alzament",
    "Printed Solid",
    "Voolt3D",
    "ABCWavePrint",
    "LANDU",
    "Ampertec",
    "AMZ3D",
    "Winkle",
    "The Filament",
    "3DE",
    "Likesilk",
    "Pinball",
    "iBOSS",
    "AGF",
    "Printbed",
    "Voxelab",
    "SainSmart",
    "FormFutura",
    "Conjure",
    "ColorFabb",
    "Slic3D",
    "CHCKX",
    "Gizmo Dorks",
];

// https://3dfilamentprofiles.com/materials
export const DEFAULT_SPOOL_MATERIALS = [
    "PLA",
    "PETG",
    "PLA+/Pro",
    "TPU",
    "ABS",
    "ASA",
    "ABS+",
    "PCTG",
    "PC",
    "PETG+",
    "HT-PLA",
    "PA6",
    "CPE",
    "PET",
    "PA (Nylon)",
    "PP",
    "PVB",
    "PA12",
    "HIPS",
    "ASA+",
    "PVA",
    "PHA",
    "TPE",
    "APLA",
    "PEBA",
    "PAHT",
    "PA612",
    "PBT",
    "PPS",
    "PC-ABS",
    "PPA",
    "PE",
    "PMMA",
    "CoPA",
    "PIPG",
    "SBS",
    "SMP",
    "PEEK",
    "SAN",
    "PCL",
    "TPR",
];

// https://3dfilamentprofiles.com/materials
export const DEFAULT_SPOOL_MATERIALTYPES = [
    "Basic",
    "Silk",
    "Matte",
    "High Speed",
    "Silk Dual",
    "Translucent",
    "Pro",
    "Other",
    "Premium",
    "CF",
    "Silk Triple",
    "95A",
    "Glow",
    "Transparent",
    "Wood",
    "PolyLite",
    "Glitter",
    "Marble",
    "HT",
    "Galaxy",
    "Sparkle",
    "Recycled",
    "High Speed Matte",
    "Metal",
    "Gradient",
    "Tough",
    "Silk Rainbow",
    "GF",
    "Easy",
    "Matte Dual",
    "Rainbow",
    "Silk Magic",
    "Max",
    "2.0",
    "Multicolor",
    "PolyTerra",
    "Rapid",
    "Fluorescent",
    "Blend",
    "HF",
    "Chameleon",
    "ECO",
    "Matte Rainbow",
    "ReFill",
    "Lite",
    "Color Change (Temp)",
    "Meta",
    "Everfil",
    "Panchroma Matte",
    "Magic",
    "Special",
    "90A",
    "Extrafill",
    "Crystal",
    "Ecofil",
    "F",
    "Panchroma Silk",
    "Color Change (UV)",
    "85A",
    "Build",
    "Flexible",
    "Panchroma Starlight",
    "Rock",
    "Silk+",
    "Gradient Matte",
    "LW",
    "Matte Tri-Color",
    "Silk-Like",
    "Panchroma CoPE",
    "Support",
    "Economy",
    "PanChroma Standard",
    "Pastello",
    "CMYK",
    "High Speed 2.0",
    "Silk Quad",
    "Ultra",
    "Silk Multi-Color",
    "Panchroma Satin",
    "Shimmer",
    "X-Strong",
    "95A HF",
    "Silk Mystic",
    "98A",
    "Neon",
    "High Speed Marble",
    "PolyMax",
    "High Gloss",
    "PolySonic",
    "Tough+",
    "EasyFil",
    "PolySmooth",
    "Foaming",
    "Gradient Twinkling",
    "Super Tough",
    "X-PLA",
    "275",
    "64D",
    "Polyflex",
    "68D (For AMS)",
    "Air",
    "FR",
    "HS Silk Dual",
    "Luminous Rainbow",
    "Panchroma Gradient Matte",
    "Aero",
    "High Speed CF",
    "Ingeo 3D870",
    "Panchroma Marble",
    "Quantum",
    "StoneFil",
    "MetalFil",
    "Panchroma Gradient",
    "Super",
    "82A",
    "nGen",
    "Panchroma Neon",
    "PTFE",
    "60D",
    "Dynamic",
    "ESD",
    "40D",
    "72D",
    "83A",
    "PolyMide",
    "Textura",
    "Blend HT LCF",
    "Conductive",
    "PolyWood",
    "Textura Flare",
    "V0",
    "55D",
    "60A",
    "Adura",
    "EVO-X Ultra Speed",
    "Ingeo 3D700",
    "Magnetite 40%",
    "Mineral",
    "ONE",
    "70A",
    "EVO-X Reforzado",
    "EVO-X Translucido",
    "Fast Gradient Matte",
    "Techfil",
    "Volcano",
];

export const DEFAULT_SPOOL_COLORS = [
    "Black",
    "White",
    "Gray",
    "Red",
    "Orange",
    "Yellow",
    "Green",
    "Blue",
    "Purple",
    "Pink",
    "Brown",
    "Beige",
    "Cyan",
    "Magenta",
    "Turquoise",
    "Gold",
    "Silver",
    "Copper",
    "Transparent",
    "Clear",
];

export const DEFAULT_OPEN_IN_APP: AppOptions["openInApp"] = [
    {
        "Orca Slicer":
            "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\OrcaSlicer\\OrcaSlicer.lnk",
    },
    {
        "Bambu Studio":
            "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Bambu Studio\\Bambu Studio.lnk",
    },
];

export const DEFAULT_LINUX_OPEN_IN_APP: AppOptions["openInApp"] = [
    {
        "Orca Slicer": "orca-slicer",
    },
    {
        "Bambu Studio": "bambu-slicer",
    },
];

export const DEFAULT_MAC_OPEN_IN_APP: AppOptions["openInApp"] = [
    {
        "Orca Slicer": "OrcaSlicer",
    },
    {
        "Bambu Studio": "BambuSlicer",
    },
];
